### ISSUE TITLE
Using it in React Native project

### ISSUE THREAD

**Issue by kandragu** [celo-tools/use-contractkit#21]
Using this module in expo react-native project, i face below issues.

`import {
  requestTxSig,
} from "@celo-tools/use-contractkit/lib/dappkit-wallet/dappkit";`

using "requestTxSig" to sign transaction, instead of module "@celo/dappkit",  coz i have to pass "TxToSignParam".

Getting errors 
![error](https://user-images.githubusercontent.com/5989381/130185224-824fdc0e-c2bb-4b8a-a73e-35c600059dd8.png)

even if i comment out  those lines still giving errors. I have problem coz the module is using "window.location.href" to store the transaction hash.

My versions:
` "@celo-tools/use-contractkit": "^1.0.6",
    "@celo/connect": "^1.0.1",
    "@celo/contractkit": "^1.2.4",
    "@celo/dappkit": "^1.2.2",
`

node_modules/@celo-tools/use-contractkit/lib/dappkit-wallet/dappkit.js is the file i'm trying to use, but i cannot find the typescript file in this repo.

Thanks.
Rahu.
BlockCash
discord: rahu#1947

**Comment by jmrossy** [comment]
@kandragu This project won't work in React Native yet. It depends on web APIs. It would be possible to make it work in React Native too but that work hasn't happened yet, sorry.

**Comment by kandragu** [comment]
@jmrossy understand the RN compatibility part.
I can make the portion of the code work for me if i can find some of the typescript source.
ex:
node_modules/@celo-tools/use-contractkit/lib/dappkit-wallet/dappkit.js is a typescript output. I cannot find its source in this repo. 

Thanks.

**Comment by aaronmgdr** [comment]
you can find that here https://github.com/celo-org/celo-monorepo/tree/master/packages/sdk/dappkit

**Comment by kandragu** [comment]
Initially i went to the above link, but if you install @celo-tools/use-contractkit, in the node_modules/@celo-tools/use-contractkit/lib/dappkit-wallet/dappkit.d.ts, the `export declare function requestTxSig(kit: ContractKit, txParams: CeloTx[], meta: DappKitRequestMeta): Promise<void>;
` which can take CeloTx[] as second argument is not there in the sdk/dappkit

![CleanShot 2021-08-24 at 10 33 34](https://user-images.githubusercontent.com/5989381/130547170-f6e69cc9-2458-43bf-91c4-929117978077.png)

Want to know how requestTxSig(...) in celo-tools is converting the CeloTx[] param to TxParams[]

**Comment by AlexBHarley** [comment]
To follow up here, I don't see use-contractkit being refactored to work with React Native.

This library makes more sense for websites where you want to connect to Ledger, WalletConnect compatible wallets, MetaMask (or any other browser extensions), etc. 

For an app, IMO you only want to connect to WalletConnect compatible wallets, so you'd be better off using the WalletConnect libraries themselves or [@celo/wallet-walletconnect](https://www.npmjs.com/package/@celo/wallet-walletconnect).
