### ISSUE TITLE
ADDING SUPPORTED WALLETS TO CONTRACT KIT

### ISSUE THREAD

**Issue by kcelestinomaria** [celo-tools/use-contractkit#3]
Hello, @eelanagaraj , @AlexBHarley how can one integrate a wallet into the supported wallets for the use-contractkit feature? Building a Celo camp product that is a wallet, and I want to integrate it into this, need your guid. Thank you.

**Comment by AlexBHarley** [comment]
Hey @kcelestinomaria, sounds great!

I'm in the middle of refactoring this module quite a bit, the idea is to now wrap ContractKit in a `connector`, this is to better handle the various flows we want to support.

You can see how some of that work is looking here https://github.com/celo-tools/use-contractkit/blob/refactor/connectors/packages/use-contractkit/src/connectors.ts. Ideally you can just add your own "Custom" connector.

What wallet are you looking to integrate? If you'd prefer more synchronous communication please jump into the Discord chat (https://chat.celo.org).

**Comment by medhakothari** [comment]
Closing stale issues, but feel free to reopen with new comments!
