### ISSUE TITLE
Wallet Connect Modal Change look

### ISSUE THREAD

**Issue by PXLFuSSeL** [celo-tools/use-contractkit#35]
Hello,

Is there a way to Change the Look of the Connect Modal? Because of i use Connect function it Just Shows Up in a weird Look, with empty Buttons.
See Here
![_20210912_110219](https://user-images.githubusercontent.com/20307656/132981781-5cbb5906-7d68-4d01-97b2-a5adb22547a4.png)

**Comment by AlexBHarley** [comment]
You might be lacking the stylesheet import, take a look at our readme [here](https://github.com/celo-tools/use-contractkit#wrap-your-application-with-contractkitprovider). If you're still having problems we can reopen this ticket.
